### PR TITLE
append multi part to file

### PR DESCRIPTION
**Pull request by NassiHarel**
This change is [Reviewable](https://reviewable.io/reviews/kube-hpc/fs-adapter.hkube/11)

### CODE REVIEW

**Review by yehiyam — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/fs-adapter.hkube/11)* status: all files reviewed, 1 unresolved discussion (waiting on @golanha and @NassiHarel)

___
*[lib/fs-adapter.js, line 61 at r1](https://reviewable.io/reviews/kube-hpc/fs-adapter.hkube/11#-MHuPWBs1YOUUHNxFpS4:-MHuPWBs1YOUUHNxFpS5:b-vndf1q) ([raw file](https://github.com/kube-hpc/fs-adapter.hkube/blob/cd5adba130ebfbb500ef225583773e7736d71ef3/lib/fs-adapter.js#L61)):*
> ```JavaScript
>             await fs.appendFile(fd, header);
>             await fs.appendFile(fd, data);
>             await fs.close(fd);
> ```

shouldn't close be in finally block?

**Comment by yehiyam** [comment]
___
*[lib/fs-adapter.js, line 61 at r1](https://reviewable.io/reviews/kube-hpc/fs-adapter.hkube/11#-MHuPWBs1YOUUHNxFpS4:-MHv14IkDgu563lApkd7:bb6ywmx) ([raw file](https://github.com/kube-hpc/fs-adapter.hkube/blob/cd5adba130ebfbb500ef225583773e7736d71ef3/lib/fs-adapter.js#L61)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

shouldn't close be in finally block?
</blockquote></details>

LGTM

**Comment by yehiyam** [comment]
___
*[lib/fs-adapter.js, line 61 at r1](https://reviewable.io/reviews/kube-hpc/fs-adapter.hkube/11#-MHuPWBs1YOUUHNxFpS4:-MHv1hbf2kqCgKVCw465:bg7igk9) ([raw file](https://github.com/kube-hpc/fs-adapter.hkube/blob/cd5adba130ebfbb500ef225583773e7736d71ef3/lib/fs-adapter.js#L61)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

LGTM
</blockquote></details>

:lgtm:

**Review by yehiyam — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/fs-adapter.hkube/11#-:-MHv1fq5E359fHNcUfXR:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @golanha)

**Review by yehiyam — APPROVED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/fs-adapter.hkube/11)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @golanha)

**Review by golanha — CHANGES_REQUESTED** [review]
I think it would simplify the encoding code, and our different storage implementations be aligned, if we always return the header separately from the data, same way we do in S3.

> *[Reviewable](https://reviewable.io/reviews/kube-hpc/fs-adapter.hkube/11#-:-MHzLbTh6Jm3-IGI_d5g:b-mvmxnr)* status: all files reviewed, 1 unresolved discussion (waiting on @NassiHarel)

___
*[lib/fs-adapter.js, line 45 at r3](https://reviewable.io/reviews/kube-hpc/fs-adapter.hkube/11#-MHzCdoSETDwe3tX_nFk:-MHzCdoSETDwe3tX_nFl:bpbbrt0) ([raw file](https://github.com/kube-hpc/fs-adapter.hkube/blob/a626c58579b381c73ade190a071e5eba501367ab/lib/fs-adapter.js#L45)):*
> ```
> end: 8 
> ```
The size of the header is the first byte. If we read it first, and use its value, we'd be more adjusted to changes made in the headers structure.
(Since the header is small, its not an issue concatenating the first byte with the rest of the header after its read.)

**Review by NassiHarel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/fs-adapter.hkube/11)* status: all files reviewed, 1 unresolved discussion (waiting on @golanha)

___
*[lib/fs-adapter.js, line 61 at r1](https://reviewable.io/reviews/kube-hpc/fs-adapter.hkube/11#-MHuPWBs1YOUUHNxFpS4:-MHuoqBv9MQ69sQiKelf:b-896fix) ([raw file](https://github.com/kube-hpc/fs-adapter.hkube/blob/cd5adba130ebfbb500ef225583773e7736d71ef3/lib/fs-adapter.js#L61)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

shouldn't close be in finally block?
</blockquote></details>

Done.
___
*[lib/fs-adapter.js, line 45 at r3](https://reviewable.io/reviews/kube-hpc/fs-adapter.hkube/11#-MHzCdoSETDwe3tX_nFk:-MHzQLmR2adWFom7IS_4:b-jyxyg8) ([raw file](https://github.com/kube-hpc/fs-adapter.hkube/blob/a626c58579b381c73ade190a071e5eba501367ab/lib/fs-adapter.js#L45)):*
<details><summary><i>Previously, golanha (Golan Hallel) wrote…</i></summary><blockquote>

> ```
> end: 8 
> ```
The size of the header is the first byte. If we read it first, and use its value, we'd be more adjusted to changes made in the headers structure.
(Since the header is small, its not an issue concatenating the first byte with the rest of the header after its read.)
</blockquote></details>

The first byte is `version`, the second byte is the `header length`,
There is not always a header, that's why we have a magic number.
what if there is no header and in the second byte there is a value of 220, instead of 8?

**Pull request merged**
